// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd2SLLpcwi63ctQgegNBK4uYU1buHWZJU',
    appId: '1:107214120845:web:07e09aa6599e2c9e04ffc4',
    messagingSenderId: '107214120845',
    projectId: 'v6j9n3dy1bhbj8mudrq0jajx104xhm',
    authDomain: 'v6j9n3dy1bhbj8mudrq0jajx104xhm.firebaseapp.com',
    storageBucket: 'v6j9n3dy1bhbj8mudrq0jajx104xhm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR_QcLf9prvqcjdKbc_r_PWg54LZAyQms',
    appId: '1:107214120845:android:dcb83b29554245b204ffc4',
    messagingSenderId: '107214120845',
    projectId: 'v6j9n3dy1bhbj8mudrq0jajx104xhm',
    storageBucket: 'v6j9n3dy1bhbj8mudrq0jajx104xhm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0BUFW6Swgc_pk-HiXQbieVEzZPdC_KCs',
    appId: '1:107214120845:ios:913ac4a73db56b0804ffc4',
    messagingSenderId: '107214120845',
    projectId: 'v6j9n3dy1bhbj8mudrq0jajx104xhm',
    storageBucket: 'v6j9n3dy1bhbj8mudrq0jajx104xhm.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
